### ISSUE TITLE
Header and Footer don't stay open

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#113]
If there is code in the header and/or footer of the program, it won't stay open when you run the program, nor do those boxes open automatically when you go to that page. As a result, you also have to click in the boxes to type before they will update and show their contents.

Example: [Try it Online!](https://lyxal.pythonanywhere.com?flags=&code=%60There's%20nothing%20above%20or%20below.%60&inputs=&header=%23%20Hey%20look%2C%20there's%20a%20bunch%20of%20stuff%20up%20here!%0A&footer=%23%20There's%20also%20a%20bunch%20of%20stuff%20down%20here!)

**Comment by Lyxal** [comment]
Gosh dang syntax highlighting changing all the textbox ids
