### ISSUE TITLE
Header and Footer are prepended/appended directly to the program

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#114]
When adding content to the header or footer, they have no newlines in between them and the program.

Expected:
```
Header Stuff
Program Stuff
More Program Stuff
Footer Stuff
```

Actual:
```
Header StuffProgram Stuff
More Program StuffFooter Stuff
```

Normally, this would not be a problem, since whitespace doesn't matter too much, but there is one important instance in which it does:
```
# Header Stuff
Program Stuff
```

Example: [Try it Online!](https://lyxal.pythonanywhere.com?flags=&code=This%20is%20the%20program%2C%20and%20since%20it's%20not%20a%20comment%2C%20it%20will%20DEFINITELY%20be%20executed%2C%20right%3F%0A%60Nope.%20And%20the%20footer%20is%20the%20same%20way%2C&inputs=&header=%23%20This%20comment%20explains%20what%20the%20program%20does.&footer=so%20this%20string%20has%20no%20newlines%20in%20it!%60)

**Comment by Lyxal** [comment]
I'll have to see what's happening internally
