### ISSUE TITLE
Online Interpreter: Keyboard always inserts text in 'code' section 

### ISSUE THREAD

**Issue by AviFS** [Lyxal/Vyxal#119]
*This is an issue for https://lyxal.pythonanywhere.com/, not Vyxal or the interpreter itself.*

**Issue:** Using the (super cool!) find-and-click keyboard at the top will always insert text into 'code' textarea, regardless of what textbox you were typing in.

**To replicate:** Select inside a different textbox eg. 'header'/'footer', and then select letters from the keyboard. They will be inserted into the 'code' area, rather than the textbox you're inside .

**Comment by ysthakur** [comment]
That would be pretty nice. The [focusout](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusout_event) event could perhaps be used to keep track of which box was last selected.

**Comment by chunkybanana** [comment]
The codemirror textareas could cause problems...

**Comment by ysthakur** [comment]
Yeah, I tried using the following inside the callback for the `DOMContentLoaded` event, but `box` turns up as `undefined`:

    for (boxId of ['header', 'code', 'footer']) {
                // box = document.getElementById(boxId);
                box = $('#' + boxId).parent().children('div').children().not('[class]').children()[0];
                const capturedId = boxId;
                console.log(`${box}, ${boxId}`)
                box.addEventListener('focusin', event => {
                    selectedBox = capturedId
                    console.log('selected' + capturedId)
                })
                box.addEventListener('onclick', event => {
                    selectedBox = capturedId
                    console.log('selected' + capturedId)
                })
                box.addEventListener('activate', event => {
                    selectedBox = capturedId
                    console.log('selected' + capturedId)
                })
                box.addEventListener('onactivate', event => {
                    selectedBox = capturedId
                    console.log('selected' + capturedId)
                })
                box.addEventListener('mouseup', event => {
                    selectedBox = capturedId
                    console.log('selected' + capturedId)
                })
        }

However, the snippet `$('#code').parent().children('div').children().not('[class]').children()[0]` yields the CodeMirror textareas in the console properly, so it's probably just that the CodeMirror stuff hasn't loaded yet and this stuff needs to be placed elsewhere.

**Comment by ysthakur** [comment]
Okay, it looks like I should have been putting that stuff inside the initcodemirror function (and only the focusin event is important). I'll make a PR later.

**Comment by ysthakur** [comment]
[This commit](https://github.com/Lyxal/Vyxal/commit/6e42e79bba1021abca71b9093527e05ee73b9976) should fix it.
