### ISSUE TITLE
Searching the elements on the site makes the OSK not insert characters

### ISSUE THREAD

**Issue by Lyxal** [Lyxal/Vyxal#121]
Okay so say you are writing a Vyxal program online. You are doing very good, but you can't remember what character is used for that fancy string distance with that very hard to remember name.

You click on the search elements box and start typing. You finish typing `distance` and see that the subscript caret is what you are looking for.

You go to click it to insert it into the codebox only to see that it doesn't actually insert it.

Confused, you click it a few more times. Nothing happens.

You remove your search query thinking that might fix it. You click the little caret. It does nothing. You click other things on the on-screen keyboard. Now no characters are being inserted at all. By now, you're wondering if the keyboard has been broken for a while, so you refresh the page just to make sure you haven't screwed it up somehow.

Once the page refreshes, you click on that tiny lil' caret again. It inserts it this time. The keyboard is working again.

It's then that you realise that VyLight integration changed all the variable names of the text areas and that the searching function wasn't updated. You then think "why did everything have to go change?!?".

That's what this issue is.

**Comment by AMiller42** [comment]
6e42e79bba1021abca71b9093527e05ee73b9976, which fixed #119, also fixes this.
