### ISSUE TITLE
g returning same as G

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#15]
When using g in the online interpreter, it returns the max instead of the min.

Example: [Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%E2%9F%A81%7C2%7C3%7C4%7C5%7C4%7C3%7C2%7C1%E2%9F%A9g&inputs=&header=&footer=)

**Comment by Lyxal** [comment]
The latest commit fixes this. Thanks for spotting this!
