### ISSUE TITLE
Unable to retrieve for loop iteration value through n

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#16]
When a variable is not specified for a `for` loop, the iteration value cannot be accessed with `←n`.

Example: [Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%E2%9F%A81%7C2%7C3%7C4%7C5%E2%9F%A9%28%E2%86%90n%29&inputs=&header=&footer=)

**Comment by Lyxal** [comment]
This isn't actually a bug. You don't use the variable syntax to get the value, you just use `n`


[Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%E2%9F%A81%7C2%7C3%7C4%7C5%E2%9F%A9%28n%29&inputs=&header=&footer=)
