### ISSUE TITLE
ǒ doesn't do anything

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#19]
ǒ doesn't modify the data passed into it. I also can't find it in the `commands.py` file at all.

Example: [Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=1%C7%92%2C%0A35%C7%92%2C%0A59%C7%92%2C%0A30-%C7%92%2C%0A33333333%C7%92%2C&inputs=&header=&footer=)

**Comment by Lyxal** [comment]
Fixed :)
