### ISSUE TITLE
'A' considers an empty list truthy

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#22]
The `A`ll command, when given an empty list, returns 1 instead of 0. In contrast, the `a`ny command returns 0.

Example: [Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%E2%9F%A8%E2%9F%A9A%2C%0A%E2%9F%A8%E2%9F%A9a%2C&inputs=&header=&footer=)

**Comment by Lyxal** [comment]
This seems to be due to how python handles empty lists. Consequently, this isn't a bug, as I want python functionality to be the default.
