### ISSUE TITLE
ǐ doesn't return titlecased

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#24]
The `ǐ` command, when applied to a string, only capitalizes the first letter, not every word.

Example: [Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%60this%20string%20doesn't%20get%20titlecased%60%C7%90&inputs=&header=&footer=)

**Comment by Lyxal** [comment]
I honestly don't know how I managed to screw up this badly. Thank you for pointing this out!
