### ISSUE TITLE
Print commands don't vectorize correctly

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#25]
When using `v` to vectorize print commands, such as `,` or `₴`, it doesn't vectorize properly. It will print the first element, then give a `list index out of range` error.

Example: [Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%E2%9F%A8%60Word%60%7C%60Other%20Word%60%7C%60Yet%20Another%60%E2%9F%A9v%2C&inputs=&header=&footer=)

**Comment by razetime** [comment]
I think vectorization is in progress for many commands, and there's like, 500 of them counting overloads. It will probably take some time.

**Comment by Lyxal** [comment]
> I think vectorization is in progress for many commands, and there's like, 500 of them counting overloads. It will probably take some time.

except it isn't.

I made a way to just generically vectorise built-ins based on their arity.

**Comment by Lyxal** [comment]
> I think vectorization is in progress for many commands, and there's like, 500 of them counting overloads. It will probably take some time.

In fact, this issue was completely unrelated to my vectorisation model
