### ISSUE TITLE
∑ doesn't vectorise correctly

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#30]
When trying to vectorise the `∑` command, it acts the same way as when it is not vectorised. 

Example: [Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%E2%9F%A8%20%E2%9F%A81%7C2%7C3%7C4%7C5%E2%9F%A9%20%7C%20%E2%9F%A810%7C20%7C30%7C40%7C50%E2%9F%A9%20%E2%9F%A9%E2%88%91%2C%0A%0A%E2%9F%A8%20%E2%9F%A81%7C2%7C3%7C4%7C5%E2%9F%A9%20%7C%20%E2%9F%A810%7C20%7C30%7C40%7C50%E2%9F%A9%20%E2%9F%A9v%E2%88%91%2C&inputs=&header=&footer=)

From example: 
```
⟨ ⟨1|2|3|4|5⟩ | ⟨10|20|30|40|50⟩ ⟩v∑

Expected output: ⟨15|150⟩
Actual output: ⟨11|22|33|44|55⟩
```

**Comment by Lyxal** [comment]
Thank you for pointing this out! I would not have found this myself.
