### ISSUE TITLE
kP and k□ are the same

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#46]
The constants `kP` and `k□` both output the full list of printable ASCII. I'm guessing `k□` is supposed to output the full ASCII list, since there are already built-ins for punctuation, whitespace, printable, uppercase, and lowercase.

Example: [Try it Online!](http://lyxal.pythonanywhere.com/?code=k%E2%96%A1,kP,)

**Comment by Lyxal** [comment]
I feel like I want to keep both for printable ASCII, but I want to know which one you think I should keep

**Comment by AMiller42** [comment]
I feel like k***P*** makes the most sense for ***P***rintable ASCII. May I ask why you want to keep both?

**Comment by Lyxal** [comment]
I just thought it might be nice for some restricted source challenges. But I'm good to just keep `kP` and reassign `k□`

**Comment by Lyxal** [comment]
Here are my proposed new values:

```python
    "□": "[[0,1],[1,0],[0,-1],[-1,0]]",
    "…": "[[0,1],[1,0]]",
    "¹": "[-1,0,1]",
```

**Comment by AMiller42** [comment]
That sounds pretty good. Ultimately, it's up to you if you want to change them or leave it how it is, I just thought it was done by accident.
