### ISSUE TITLE
Diagraphs don't vectorise

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#52]
Diagraphs (`∆²`, `ÞT`, `øD`, etc.) don't properly vectorise with `v`.

Example: [Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%E2%9F%A8%60hello%60%7C%60world%60%E2%9F%A9v%C3%B8D&inputs=&header=&footer=)

**Comment by Lyxal** [comment]
Closed because it's fixed
