### ISSUE TITLE
Unable to stop interpreter mid-execution

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#53]
It looks like this snippet from main.html is supposed to allow you to kill the execution at any point, but it doesn't work.
``` javascript
function do_run() {
    if (!run.innerHTML.includes("fa-spin")) {
        ...code to start execution...           
    } else {
        $.post("/kill", { session: session }, res => 0);
    }

$("#run_button").on("click", e => {do_run();});
```

**Comment by Lyxal** [comment]
This happens because pythonanywhere [doesn't allow multithreading](https://www.pythonanywhere.com/forums/topic/1563/).
