### ISSUE TITLE
x has the wrong functionality

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#57]
The `x` command moves the context level down, but according to `elements.md`:

> \* call current function # recursion. Prints entire stack if not in a function/lambda

**Comment by Lyxal** [comment]
This is actually a recent change. The documentation is correct here

**Comment by AMiller42** [comment]
The documentation is correct, but the command’s function is not. commands.py, line 103: `"x": ("context_level -= 1", 0)`

Example: [Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%40factorial%3A1%7C0%3D%5B1%7Cn1-x*%5D%3B%205%20%40factorial%3B&inputs=&header=&footer=)
