### ISSUE TITLE
`⋎` Doesn't like repeated characters in strings

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#79]
If a character appears multiple times in the suffix and prefix of the strings, it doesn't work properly.

Example ('g' appears twice in suffix and prefix): [Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%60agog%60%20%60goga%60%20%E2%8B%8E&inputs=&header=&footer=)

Expected:
``` `agog` `goga` ⋎ || agoga ```

**Comment by Lyxal** [comment]
B...but it _does_ do that. The link you provided gives the expected result.

**Comment by AMiller42** [comment]
What the heck!? I *swear* it wasn’t working earlier. Nothing to worry about, I guess. Sorry about that. I have no idea what happened.

**Comment by AMiller42** [comment]
Wait a minute, I think this is what I was thinking of: [Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%60aggg%60%20%60ggga%60%20%E2%8B%8E&inputs=&header=&footer=)

It should be `aggga` instead of `agggga`.

**Comment by Lyxal** [comment]
Aha. Now I've got something to look into!

**Comment by Lyxal** [comment]
On further inspection, it seems that the expected output should be `aggg`.

This is still a valid bug that needs fixing.

**Comment by Lyxal** [comment]
okay nevermind I clearly didn't know how suffixes work
