### ISSUE TITLE
Generators causing problems because they aren't lists

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#82]
There's several things that are broken because `generators != lists`. I'll keep listing them as I find/think of them, but for know, all I can think of is map lambda: [Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%E2%9F%A81%7C2%7C3%7C4%7C5%E2%9F%A9s%C6%9B%2C&inputs=&header=&footer=) I suppose the problem could also be with printing, but I haven't looked too closely at it.

**Comment by razetime** [comment]
There was a problem earlier where lyxal clarified that infinite generators were being converted to lists, which obviously stalledthe program forever. Not sure if that was fixed, but it might be related.

**Comment by Lyxal** [comment]
This is something that will take more than a quick fix - it would require a complete reworking of how the Generator class works.

I suppose this is the drawbacks of lazy evaluation.

Maybe this gets addressed in the experimental branch, maybe not. We'll see.

**Comment by ysthakur** [comment]
The map lambda doing that makes sense, I guess - it'd be better for it not to evaluate immediately in case there's an infinite generator or something. I guess a for loop could be used as an alternative? Or perhaps a `to_list` function?

**Comment by Lyxal** [comment]
https://chat.stackexchange.com/rooms/106764/conversation/how-and-why-are-generators

**Comment by Lyxal** [comment]
(feel free to re-open though if you think there's still something to fix)
