### ISSUE TITLE
`Ŀ` broken as `repeat_until_false`

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#88]
When using the `Ŀ` command as `repeat_until_false`, instead of returning an object of type `<class '__main__.Generator'>`, it returns an object of type `<class 'generator'>`, which is not something that commands are overloaded for, so they fail.

For example: [Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%CE%BBt9%3D%3B%20%CE%BB%E2%80%BA%3B%20%E2%9F%A81%7C2%7C3%7C4%7C5%E2%9F%A9%20%C4%BF%2C&inputs=&header=&footer=)

**Comment by ysthakur** [comment]
[This commit](https://github.com/Lyxal/Vyxal/commit/f031da3e7398039cffcb7984edcd7c8aaa0c1d1c) should fix it, it was just that `Generator(gen())` was needed instead of `gen()`.
