### ISSUE TITLE
`C` flag doesn't work on lists of numbers

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#98]
[Try it Online!](https://lyxal.pythonanywhere.com?flags=C&code=%E2%9F%A81%7C123%7C12345%7C1234567%7C12345%7C123%7C1%E2%9F%A9&inputs=&header=&footer=)

**Comment by Lyxal** [comment]
Convert it to a list of strings using `vS` like a real gamer.

**Comment by AMiller42** [comment]
*\* adds `vS` flag to convert top of stack to list of strings before printing \**

**Comment by razetime** [comment]
`vSf` is the general thing top golfing languages do before printing output for lists containing non-integers.
