### ISSUE TITLE
`Q` doesn't do implicit output

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#99]
When terminating a program with the `Q` command, there is no implicit output. This may be intended behavior, but I wanted to mention it anyway. What *is* probably a bug, however, is that it still doesn't do implicit output, even if you use the `o` flag to force implicit output.

Example: [Try it Online!](https://lyxal.pythonanywhere.com?flags=o&code=69%20Q&inputs=&header=&footer=)

**Comment by ysthakur** [comment]
That makes sense - the implementation of `Q` is literally `exit()`. Lemme make a PR to make it print before exiting with the `o` flag.
